/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package odissey;
import Cliente.XmlWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import odissey.Sign_in;
import odissey.odysseyppcliente;
/**
 *
 * @author maesly
 */
public class VentanaLogIn extends javax.swing.JFrame {
    
    String nombreUsuario, contraseña;
    Sign_in validaciones = new Sign_in();
    odysseyppcliente cliente = new odysseyppcliente();
    /**
     * Creates new form VentanaLogIn
     */
    public VentanaLogIn() {
        initComponents();
        this.setBounds(250, 100, 500, 500);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContrasena = new javax.swing.JLabel();
        jButtonContinuar = new javax.swing.JButton();
        jButtonAtras = new javax.swing.JButton();
        jLabelfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setToolTipText("Usuario");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(190, 70, 220, 28);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(190, 170, 220, 28);

        jLabelUsuario.setFont(new java.awt.Font("Century Schoolbook L", 2, 18)); // NOI18N
        jLabelUsuario.setForeground(new java.awt.Color(248, 241, 241));
        jLabelUsuario.setText("Ingrese el nombre de usuario:");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(180, 40, 280, 24);

        jLabelContrasena.setFont(new java.awt.Font("Century Schoolbook L", 2, 18)); // NOI18N
        jLabelContrasena.setForeground(new java.awt.Color(248, 241, 241));
        jLabelContrasena.setText("Ingrese la contraseña:");
        getContentPane().add(jLabelContrasena);
        jLabelContrasena.setBounds(190, 130, 280, 30);

        jButtonContinuar.setText("Continuar...");
        jButtonContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonContinuar);
        jButtonContinuar.setBounds(350, 400, 120, 40);

        jButtonAtras.setText("Atras");
        jButtonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtras);
        jButtonAtras.setBounds(30, 400, 110, 40);

        jLabelfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fa.png"))); // NOI18N
        jLabelfondo.setText("jLabel3");
        getContentPane().add(jLabelfondo);
        jLabelfondo.setBounds(0, 0, 740, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButtonContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarActionPerformed
        // TODO add your handling code here:
        VentanaReproductor ventanaReproductor = new VentanaReproductor();
        
       
        nombreUsuario = jTextField1.getText();
        contraseña = jPasswordField1.getText();
        XmlWriter writer = new XmlWriter();
        String t = writer.writeUser("1", "1", "1", jTextField1.getText(),jPasswordField1.getText(),"1","1");
        try {
            if(cliente.login(t) == 1){
                System.out.println("Ingresó correctamente");
                ventanaReproductor.setVisible(true);
            }else{
                System.out.println("Error al ingresar nombre de usuario o contraseña");
                ventanaReproductor.setVisible(true);
            }
        } catch (IOException ex) {
            Logger.getLogger(VentanaSignIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButtonContinuarActionPerformed

    private void jButtonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtrasActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_jButtonAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaLogIn().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtras;
    private javax.swing.JButton jButtonContinuar;
    private javax.swing.JLabel jLabelContrasena;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JLabel jLabelfondo;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
