package odissey;
import Cliente.XmlWriter;

/**
 *
 * @author maesly
 */
public class VentanaSignIn extends javax.swing.JFrame {
    String nombre,apellido,edad,nombreUsuario,contraseña = "",amigos, generos = "";

    /**
     * Creates new form VentanaSignIn
     */
    public VentanaSignIn() {
        initComponents();
        this.setBounds(250, 100, 550, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        checkbox5 = new java.awt.Checkbox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign In");
        setMinimumSize(new java.awt.Dimension(550, 475));
        getContentPane().setLayout(null);

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(330, 460, 130, 30);

        jTextField1.setText("Nombre");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 40, 200, 40);

        jPasswordField1.setText("jPasswordField1");
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(20, 230, 200, 40);

        jTextField2.setText("Apellidos");
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 40, 200, 40);

        jTextField3.setText("Edad");
        getContentPane().add(jTextField3);
        jTextField3.setBounds(290, 130, 200, 40);

        jTextField4.setText("Amigos");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField4);
        jTextField4.setBounds(290, 230, 200, 40);

        jTextField5.setText("Nombre de usuario");
        getContentPane().add(jTextField5);
        jTextField5.setBounds(20, 130, 200, 40);

        checkbox1.setBackground(new java.awt.Color(80, 80, 80));
        checkbox1.setForeground(new java.awt.Color(247, 245, 245));
        checkbox1.setLabel("Rock and Roll");
        getContentPane().add(checkbox1);
        checkbox1.setBounds(30, 340, 120, 19);

        checkbox2.setBackground(new java.awt.Color(80, 80, 80));
        checkbox2.setForeground(new java.awt.Color(247, 245, 245));
        checkbox2.setLabel("Disco");
        getContentPane().add(checkbox2);
        checkbox2.setBounds(30, 360, 120, 19);

        checkbox3.setBackground(new java.awt.Color(80, 80, 80));
        checkbox3.setForeground(new java.awt.Color(247, 245, 245));
        checkbox3.setLabel("Rock");
        getContentPane().add(checkbox3);
        checkbox3.setBounds(30, 320, 120, 19);

        checkbox4.setBackground(new java.awt.Color(80, 80, 80));
        checkbox4.setForeground(new java.awt.Color(247, 245, 245));
        checkbox4.setLabel("Pop");
        getContentPane().add(checkbox4);
        checkbox4.setBounds(30, 380, 120, 19);

        checkbox5.setBackground(new java.awt.Color(80, 80, 80));
        checkbox5.setForeground(new java.awt.Color(247, 245, 245));
        checkbox5.setLabel("Country");
        checkbox5.setName(""); // NOI18N
        getContentPane().add(checkbox5);
        checkbox5.setBounds(30, 400, 120, 19);

        jLabel1.setForeground(new java.awt.Color(216, 234, 238));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 90, 30);

        jLabel2.setForeground(new java.awt.Color(216, 234, 238));
        jLabel2.setText("Nombre de Usuario");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 160, 30);

        jLabel4.setForeground(new java.awt.Color(216, 234, 238));
        jLabel4.setText("Apellidos: ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 10, 100, 18);

        jLabel5.setForeground(new java.awt.Color(216, 234, 238));
        jLabel5.setText("Contraseña: ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 210, 120, 20);

        jLabel6.setForeground(new java.awt.Color(216, 234, 238));
        jLabel6.setText("Géneros");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 290, 80, 18);

        jLabel7.setForeground(new java.awt.Color(216, 234, 238));
        jLabel7.setText("Edad: ");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 100, 49, 18);

        jLabel8.setForeground(new java.awt.Color(254, 254, 254));
        jLabel8.setText("Ingrese sus amigos ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 180, 140, 40);

        jLabel9.setForeground(new java.awt.Color(251, 249, 249));
        jLabel9.setText("separados por una coma: ");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 210, 210, 18);

        jLabel3.setBackground(new java.awt.Color(16, 0, 59));
        jLabel3.setForeground(new java.awt.Color(255, 233, 233));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fa.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-140, -100, 720, 670);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        VentanaPrincipal ventana = new VentanaPrincipal();
        ventana.setVisible(true); //Hacemos visible la nueva venta
        this.setVisible(false); //Cerramos la ventana anterior
        
        
        nombre = jTextField1.getText();
        apellido = jTextField2.getText();
        edad = jTextField3.getText();
        amigos = jTextField4.getText();
        nombreUsuario = jTextField5.getText();
        contraseña = jPasswordField1.getText();
        
        XmlWriter writer = new XmlWriter();
        writer.writeUser(jTextField1.getText(), jTextField2.getText(),
                        jTextField3.getText(), jTextField5.getText(),
                        jPasswordField1.getText(), jTextField4.getText(),
                        "hola");
        
       
        
        //Usuarios usuarios = new Usuarios(nombre, nombreUsuario, apellido, edad, contraseña, amigos, generos);
        //usuarios.imprimirUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private java.awt.Checkbox checkbox5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
